# Generated by Django 3.0.5 on 2020-04-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='seatNo',
            new_name='seatType',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='ticketId',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
