# Generated by Django 3.0.5 on 2020-04-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200421_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='reservationStatus',
        ),
    ]
