# Generated by Django 3.0.5 on 2020-04-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_passenger_reservationstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='bookedBy',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='traindetails',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.RemoveField(
            model_name='trainstatus',
            name='trainNo',
        ),
        migrations.DeleteModel(
            name='TT',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
        migrations.DeleteModel(
            name='TrainStatus',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
